#!/bin/bash

cpucount=`cat /proc/cpuinfo|grep processor|wc -l`

FLROOT=/sys/devices/system/cpu

if [ $# -lt 1 ]
then
	echo "USAGE: cpufreqctl [OPTION] [VALUE]"
	echo "OPTIONS [gov|list|driver|info|freq|set|turbo|min|max|boost|minf|maxf]"
	echo "Current driver"
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
	echo "Available governors"
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
	echo "Current cpu0 governor"
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	exit
fi
if [ $1 = "gov" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
		exit
	fi
	i=0
	while [ $i -ne $cpucount ]
	do
		FLNM="$FLROOT/cpu"$i"/cpufreq/scaling_governor"
		echo "Setting $FLNM to " $2
		echo $2 > $FLNM
		i=`expr $i + 1`
	done
	exit
fi
if [ $1 = "list" ]
then
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
	exit
fi
if [ $1 = "driver" ]
then
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_driver
	exit
fi
if [ $1 = "info" ]
then
	i=0
	V=0
	M=$(cat "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq")
	while [ $i -ne $cpucount ]
	do
	    V=$(cat "/sys/devices/system/cpu/cpu"$i"/cpufreq/scaling_cur_freq")
	    if [[ $V > $M ]]
	    then
	        M=$V
	    fi
		i=`expr $i + 1`
	done
	echo "$M"
	exit
fi
if [ $1 = "info_avg" ]
then
	i=1
	V=0
	M=$(cat "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq")
	while [ $i -ne $cpucount ]
	do
	    V=$(cat "/sys/devices/system/cpu/cpu"$i"/cpufreq/scaling_cur_freq")
	    M=`expr $M + $V`
	    i=`expr $i + 1`
	done
	echo `expr $M / $cpucount`
	exit
fi
if [ $1 = "freq" ]
then
	cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
	exit
fi
if [ $1 = "set" ]
then
	if [ $# = 1 ]
	then
		echo "available frequences"
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
		echo "current cpu frequence"
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
		exit
	fi
	i=0
	while [ $i -ne $cpucount ]
	do
		FLNM="$FLROOT/cpu"$i"/cpufreq/scaling_setspeed"
		echo "Setting $FLNM to " $2
		echo $2 > $FLNM
		i=`expr $i + 1`
	done
	exit
fi
if [ $1 = "turbo" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/intel_pstate/no_turbo
		exit
	fi
	echo "Setting TURBO to " $2
	echo $2 > /sys/devices/system/cpu/intel_pstate/no_turbo
	exit
fi
if [ $1 = "min" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/intel_pstate/min_perf_pct
		exit
	fi
	echo "Setting MIN to " $2
	echo $2 > /sys/devices/system/cpu/intel_pstate/min_perf_pct
	exit
fi
if [ $1 = "max" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/intel_pstate/max_perf_pct
		exit
	fi
	echo "Setting MAX to " $2
	echo $2 > /sys/devices/system/cpu/intel_pstate/max_perf_pct
	exit
fi
if [ $1 = "boost" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/cpufreq/boost
		exit
	fi
	echo "Setting BOOST to " $2
	echo $2 > /sys/devices/system/cpu/cpufreq/boost
	exit
fi
if [ $1 = "minf" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
		exit
	fi
	i=0
	while [ $i -ne $cpucount ]
	do
		FLNM="$FLROOT/cpu"$i"/cpufreq/scaling_min_freq"
		echo "Setting $FLNM to " $2
		echo $2 > $FLNM
		i=`expr $i + 1`
	done
	exit
fi
if [ $1 = "maxf" ]
then
	if [ $# = 1 ]
	then
		cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
		exit
	fi
	i=0
	while [ $i -ne $cpucount ]
	do
		FLNM="$FLROOT/cpu"$i"/cpufreq/scaling_max_freq"
		echo "Setting $FLNM to " $2
		echo $2 > $FLNM
		i=`expr $i + 1`
	done
	exit
fi
if [ $1 = "install" ]
then
    echo 'installing cpufreqctl...'
    cp $0 /usr/bin/
    echo 'installing policy...'
	cp $(dirname "$(readlink -f "$0")")/konkor.cpufreq.policy /usr/share/polkit-1/actions/
	exit
fi

