source 'https://rubygems.org'

# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 3.7.2"

# Site dependencies
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
